[window]
opacity = 0.9
dimensions = { columns = 120, lines = 25 }
padding = { x = 3, y = 5 }

[font]
normal = { family = "Source Code Pro", style = "Regular" }
offset = { x = 1, y = 0 }
size = 16

[mouse]
hide_when_typing = true

[cursor]
style = { shape = "Beam", blinking = "On"}
